# Gradle Properties
org.gradle.jvmargs = -Xmx3G

mod_version = 1.0.1
mod_id = librarian_filter
mod_name = Easy Villager Trade Reroll
root_package = com.gbdhapa
minecraft_version = 1.12.2
minecraft_username = Developer
enable_shadow = false
generate_sources_jar = false
generate_javadocs_jar = false
enable_lwjglx = true
use_access_transformer = false
enable_foundation_debug = false
is_coremod = false
