plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

base {
	archivesName = "librarian-filter-quilt-${project.minecraft_version}"
}

repositories {
	maven {
		name = 'Quilt'
		url = 'https://maven.quiltmc.org/repository/release/'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"librarian-filter" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation project(":common")
	
	implementation "org.quiltmc:quilt-loader:${project.quilt_loader_version}"
	implementation "org.quiltmc.quilted-fabric-api:quilted-fabric-api:${project.quilted_fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching(["quilt.mod.json", "fabric.mod.json"]) {
		expand "version": version
	}
}
