plugins {
	id 'dev.architectury.loom'
	id 'maven-publish'
}

base {
	archivesName = "librarian-filter-common"
}

loom {
    // Common module
}

repositories {
	maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	
	mappings loom.officialMojangMappings()
	compileOnly "org.spongepowered:mixin:0.8.5"
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
